name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Az CLI login
      uses: azure/login@v1
      with:
          client-id: "3649039c-8415-459d-af3a-b29d75612fbc"
          tenant-id: "9604c138-e5d6-4c98-a4fc-2d67d6fd954e"
          subscription-id: "4b88b802-abfd-413d-9c62-a3357ce9b003"
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
#     - uses: actions/checkout@v3
#     # Build 
#     - name: Build Docker Image
#       run: docker build -t hello .
#     # Run 
#     - name: Run Docker Image
#       run: docker run hello
#     # Curl 
#     - name: If fail
#       if: failure()
#       run: echo "Failed"
#     - name: If success
#       if: success()
#       run: echo "Success"
      
      
      
      
      
