name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
#     - name: Login via Az module
#       uses: azure/login@v1
#       with:
#         creds: ${{secrets.AZURE_CREDENTIALS}}
#         enable-AzPSSession: true 
  
    - name: 'Run Azure CLI commands'
      run: |
          az login -u "46e799f7-128e-4722-b665-596e16d9291c" -p "2-J8Q~dQpc4ENNKZ0Usr.TxxBbznPVB2j95swa55"
          az account show
          az group list
          pwd 
          
#     - uses: actions/checkout@v3
#     # Build 
#     - name: Build Docker Image
#       run: docker build -t hello .
#     # Run 
#     - name: Run Docker Image
#       run: docker run hello
#     # Curl 
#     - name: If fail
#       if: failure()
#       run: echo "Failed"
#     - name: If success
#       if: success()
#       run: echo "Success"
      
      
      
      
      
